# Generated by Django 4.2 on 2026-02-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='subject',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
